services:

  database:
    image: mysql:8.4

    container_name: chiron_academy_database

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chironAcademyData

    ports:
      - "3306:3306"

    volumes:
      - chiron_academy_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: chiron_academy_backend

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      PORT: 3000

      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: chironAcademyData
      DB_USER: root
      DB_PASSWORD: root

      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      database:
        condition: service_healthy


volumes:
  chiron_academy_data: